services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./liste_des_prenoms.csv:/docker-entrypoint-initdb.d/liste_des_prenoms.csv

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080